id: P009458
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD193
  title: གཏིང་སྐྱེས་རྫོང་གི་དཀར་ཆག
  author: ''
  volumes:
    75a2cc193d204668929b313abac2976c:
      image_group_id: I4PD4605
      title: ''
      volume_number: 1
      total_pages: 1260
