id: IE25FAA95
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:52:26+00:00'
last_modified: '2022-06-08T11:11:09.625895+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD193
  title: གཏིང་སྐྱེས་རྫོང་གི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    949C:
      image_group_id: I4PD4605
      title: ''
      total_pages: 1260
      order: 1
      base_file: 949C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
